### ISSUE TITLE
use lightGBM_stacking pipeline raise error

### ISSUE THREAD

**Issue by HuangZhanPeng** [neptune-ml/open-solution-home-credit#194]
There are two things that will make the processing of your issue faster:
1. Make sure that you are using the latest version of the code,
1. In case of bug issue, it would be nice to provide more technical details such like execution command, error message or script that reproduces your bug.
#

Thanks!

Kamil & Jakub,

*core contributors to the [minerva.ml](https://minerva.ml)*

while I run the script `python -W ignore main.py -- train_evaluate_predict_cv --pipeline_name lightGBM_stacking`

it raise error like following:

```
2018-08-10 21:03:04 steppy >>> done: initializing experiment directories
2018-08-10 21:03:04 steppy >>> Step light_gbm_fold_0 initialized
2018-08-10 21-03-04 home-credit >>> Start pipeline fit and transform on train
2018-08-10 21:03:04 steppy >>> cleaning cache...
2018-08-10 21:03:04 steppy >>> cleaning cache done
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    main()
  File "/opt/anaconda2/envs/python3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda2/envs/python3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda2/envs/python3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda2/envs/python3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda2/envs/python3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 78, in train_evaluate_predict_cv
    pipeline_manager.train_evaluate_predict_cv(pipeline_name, model_level, dev_mode, submit_predictions)
  File "/data1/huangzp/kaggle/home_risk_lightgbm/src/pipeline_manager.py", line 37, in train_evaluate_predict_cv
    train_evaluate_predict_cv(pipeline_name, model_level, dev_mode, submit_predictions)
  File "/data1/huangzp/kaggle/home_risk_lightgbm/src/pipeline_manager.py", line 173, in train_evaluate_predict_cv
    train_evaluate_predict_cv_first_level(pipeline_name, dev_mode, submit_predictions)
  File "/data1/huangzp/kaggle/home_risk_lightgbm/src/pipeline_manager.py", line 285, in train_evaluate_predict_cv_first_level
    model_level='first')
  File "/data1/huangzp/kaggle/home_risk_lightgbm/src/pipeline_manager.py", line 428, in _fold_fit_evaluate_predict_loop
    fold_id, pipeline_name, model_level)
  File "/data1/huangzp/kaggle/home_risk_lightgbm/src/pipeline_manager.py", line 517, in _fold_fit_evaluate_loop
    pipeline.fit_transform(train_data)
  File "/opt/anaconda2/envs/python3/lib/python3.6/site-packages/steppy/base.py", line 310, in fit_transform
    step_inputs[input_data_part] = data[input_data_part]
KeyError: 'input'
```

**Comment by jakubczakon** [comment]
Hi there @HuangZhanPeng .
When you run second level models you need to specify this in the command.
In your case:

```bash
python -W ignore main.py -- train_evaluate_predict_cv --pipeline_name lightGBM_stacking --model_level second
```

should get the job done.

**Comment by HuangZhanPeng** [comment]
Dear jakubczakon:
Thanks for answer my question! It is a very great pineline for kaggle! I learn a lot and thanks for sharing!
best, 
Huang

**Comment by jakubczakon** [comment]
It seems that your `out_of_fold_predictions` folder is empty. 

The format that is expected is:

```bash
model1_oof_train.csv
model1_oof_test.csv
model2_oof_train.csv
model2_oof_test.csv
```

so you need to rename stuff that is trained in the first level if you want to use it here.

**Comment by tsingjinyun** [comment]
@jakubczakon ,how to generate out_of_fold_predictions/model1_oof_train.csv? after run 
python main.py -- train_evaluate_predict_cv --pipeline_name lightGBM 
no file save at out_of_fold_predictions

**Comment by jakubczakon** [comment]
That file is saved in your experiment directory. Since you are running lighGBM pipeline those files are most likely called:

* `lightGBM_stacking_out_of_fold_train_predictions.csv` 
* `lightGBM_stacking_out_of_fold_test_predictions.csv ` 

just copy them to the out_of_fold_predictions directory and rename.

**Comment by gagolucasm** [comment]
Hi, after copying the predictions to the folder, I am getting this issue:

2```
018-08-28 08:35:13 steppy >>> Step stacking_features_fold_0, adapting inputs...
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    main()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 78, in train_evaluate_predict_cv
    pipeline_manager.train_evaluate_predict_cv(pipeline_name, model_level, dev_mode, submit_predictions)
  File "/home/ubuntu/open-solution-home-credit/src/pipeline_manager.py", line 37, in train_evaluate_predict_cv
    train_evaluate_predict_cv(pipeline_name, model_level, dev_mode, submit_predictions)
  File "/home/ubuntu/open-solution-home-credit/src/pipeline_manager.py", line 175, in train_evaluate_predict_cv
    train_evaluate_predict_cv_second_level(pipeline_name, submit_predictions)
  File "/home/ubuntu/open-solution-home-credit/src/pipeline_manager.py", line 350, in train_evaluate_predict_cv_second_level
    model_level='second')
  File "/home/ubuntu/open-solution-home-credit/src/pipeline_manager.py", line 437, in _fold_fit_evaluate_predict_loop
    fold_id, pipeline_name, model_level)
  File "/home/ubuntu/open-solution-home-credit/src/pipeline_manager.py", line 533, in _fold_fit_evaluate_loop
    output_valid = pipeline.transform(valid_data)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/steppy/base.py", line 360, in transform
    step_inputs[input_step.name] = input_step.transform(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/steppy/base.py", line 360, in transform
    step_inputs[input_step.name] = input_step.transform(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/steppy/base.py", line 366, in transform
    step_output_data = self._cached_transform(step_inputs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/steppy/base.py", line 469, in _cached_transform
    raise ValueError('No transformer cached {}'.format(self.name))
ValueError: No transformer cached stacking_features_fold_0

```
Any clue of what can be going on?

**Comment by gagolucasm** [comment]
Nevermind, I am sorry. The issue was that I had only one model into out_of_fold_predictions folder.
